- name: app setup
  ansible.builtin.import_roles:
    name: common
    tasks_from: app-setup

- name: nodejs
  ansible.builtin.import_roles:
    name: common
    tasks_from: nodejs

- name: mongodb setup
  ansible.builtin.import_roles:
    name: common
    tasks_from: mongodb-setup

- name: systectl service
  ansible.builtin.import_roles:
    name: common
    tasks_from: systemd
