- name: app setup
  ansible.builtin.import_roles:
    name: common
    tasks_from: app-setup

- name: go
  ansible.builtin.import_roles:
    name: common
    tasks_from: go

- name: Setup catalogue service
  ansible.builtin.import_roles:
    name: common
    tasks_from: systemd
