- name: app setup
  ansible.builtin.import_roles:
    name: common
    tasks_from: app-setup

- name: python
  ansible.builtin.import_roles:
    name: common
    tasks_from: python

- name: Setup catalogue service
  ansible.builtin.import_roles:
    name: common
    tasks_from: systemd
