- name: variable form promt
  hosts: localhost
  vars_prompt:
    - name: USERNAME
      promt: Please enter your USERNAME
      private: false #user can see what they are entering
    - name: PASSWORD
      promt: Please enter your password
      private: ture #user can't see what they are entering
  tasks:
    - name: print and check the values
      ansible.builtin.debug:
        msg: "username is : {{USERNAME}}, password is: {{PASSWORD}}"
