- name: loops
  hosts: localhost
  tasks:
    - name: print persons
      ansible.builtin.debug:
        msg: "Hello all {{item}}" # item is a default value.
      loop:
        - Ram
        - raja
        - Jam
        - joshy
