- name: Install remi release
  ansible.builit.dnf:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

- name: Enable redis
  ansible.builit.command: dnf module enable redis:remi-6.2 -y

- name: Install Redis
  ansible.builtin.dnf:
    name: redis
    state: present

- name: allow remote conncetions # Update listen address from 127.0.0.1 to 0.0.0.0 in /etc/mongod.conf
  ansible.builit.replace:
    path: /etc/redis/redis.conf
    regexp: "127.0.0.1"
    replace: "0.0.0.0"

- name: start and enable redis
  ansible.builit.service:
    name: redis
    state: restarted
    enable: yes
