- name: Install Mysql clinet
  ansible.builtin.dnf:
    name: mysql
    state: present

- name: Check if cities schema exists
  ansible.builtin.command:
    cmd: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities';"
    register: schema

- name: print output
  ansible.builtin.debug:
    msg: "schema output: {{schema}}"

- name: Load cities data
  ansible.builtin.shell: mysql -h {{MYSQL_HOST}} -uroot -p{{mysql_password}} < /app/schema/shipping.sql
  when: schema.stdout != "1"
